// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	datacatalog "idrm/api/internal/handler/datacatalog"
	sysmenu "idrm/api/internal/handler/sys/menu"
	"idrm/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// Data catalog routes
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/draft",
				Handler: datacatalog.SaveDraftHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/draft/:id",
				Handler: datacatalog.GetDraftHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/draft/:id",
				Handler: datacatalog.DeleteDraftHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/drafts",
				Handler: datacatalog.ListDraftsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/data-catalog"),
	)

	// Menu routes - wrap struct-based handlers to http.HandlerFunc
	createMenuHandler := sysmenu.NewCreateMenuHandler(serverCtx)
	deleteMenuHandler := sysmenu.NewDeleteMenuHandler(serverCtx)
	getMenuHandler := sysmenu.NewGetMenuHandler(serverCtx)
	getMenuTreeHandler := sysmenu.NewGetMenuTreeHandler(serverCtx)
	updateMenuHandler := sysmenu.NewUpdateMenuHandler(serverCtx)
	listMenusHandler := sysmenu.NewListMenusHandler(serverCtx)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/menu",
				Handler: createMenuHandler.CreateMenu,
			},
			{
				Method:  http.MethodDelete,
				Path:    "/menu/:id",
				Handler: deleteMenuHandler.DeleteMenu,
			},
			{
				Method:  http.MethodGet,
				Path:    "/menu/:id",
				Handler: getMenuHandler.GetMenu,
			},
			{
				Method:  http.MethodGet,
				Path:    "/menu/tree",
				Handler: getMenuTreeHandler.GetMenuTree,
			},
			{
				Method:  http.MethodPut,
				Path:    "/menu/:id",
				Handler: updateMenuHandler.UpdateMenu,
			},
			{
				Method:  http.MethodGet,
				Path:    "/menus",
				Handler: listMenusHandler.ListMenus,
			},
		},
		rest.WithPrefix("/api/v1/system"),
	)
}
